#------------------------------------------------------------------------
# Asigna un nombre al trabajo
#------------------------------------------------------------------------

#PBS -N DTW

#------------------------------------------------------------------------
# Asigna el trabajo a una cola
#------------------------------------------------------------------------

#PBS -q ampl-work

#------------------------------------------------------------------------
# Configura la cantidad de nodos a utilizar.
# nodes indica la cantidad de maquinas y ppn la cantidad de procesos
# por nodo.
# Si queremos solicitar 3 procesos con 1 por nodo.
# EJ. -l nodes=3
# Si queremos solicitar 8 procesos con 2 procesos por nodo.
# EJ. -l nodes=4:ppn=2
# También se pueden solicitar procesadores como
# EJ. -l ncpus=12
# O memoria
# EJ. -l mem=12
#------------------------------------------------------------------------

#PBS -l ncpus=32

#------------------------------------------------------------------------
#  Ejecuta el trabajo
#------------------------------------------------------------------------

module load python/3.4.3
python3 /home/tayany/memoria/app.py
